config/routes.rb
Rails.application.routes.draw do
  resources :book_chapters
  resources :books
  devise_for :users
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #

  resources :reviews, only: [] do
    collection do
      post :request
      post :inform_authors
    end
  end

  scope('(/:locale)') do
    resources :blog_posts do
      member do
        get :pdf
      end
    end

    resource :locales

    # get 'welcome'=>  'welcome#index'
    match '/welcome' => 'welcome#index', :via => [:get, :post]

    match '/names' => 'names#form', :via => [:get, :post]
  end

  root 'blog_posts#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

  validates :title, :body, presence: true

  #has_one_attached :image
  has_attached_file :image, style: { medium: "100x100>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user

  include Rails.application.helpers


  def pdf_path
    Rails.root.join('tmp', "#{self.id}.pdf")
    
  end # #pdf_path

  def to_pdf
    Prawn::Document.generate(pdf_path) do |pdf|
      pdf.text self.title
      pdf.text markdown(self.body)
    end
    File.open(pdf_path)
  end # #to_pdf
end

app/models/book.rb
class Book < ApplicationRecord
  include FlagShihTzu

  has_many :book_chapters
  has_flags(
    1 => :published,
    2 => :on_sale
  )

  accepts_nested_attributes_for :book_chapters, reject_if: proc {|attributes|
    attributes['_destroy'].blank? and attributes['title'].blank? 
  }, allow_destroy: true

end

app/models/book_chapter.rb
class BookChapter < ApplicationRecord
  belongs_to :book

  has_and_belongs_to_many :authors, class_name: 'User', join_table: :book_chapters_authors

  has_and_belongs_to_many :reviewers, class_name: 'User', join_table: :book_chapters_reviewers
  
end

app/models/name_api.rb
class NameApi
  class << self
    
    def site
     URI('http://www.thomas-bayer.com/restnames/name.groovy')
    end # .site

    def get_frequency(name)
      Hash.from_xml(
        RestClient.get("#{self.site}?name=#{name}")
      )[:restnames][:nameinfo]
    end # .get_frequency
  end # class << self

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
    :omniauthable, :registerable, 
    :recoverable, :rememberable, :trackable, :validatable

  has_many :blog_posts
end

app/models/vat_id.rb
class VatId

  class << self

    def site
      'https://evatr.bff-online.de/evatrRPC'
    end # #site

    def get(ust_id)
      Hash.from_xml( RestClient.get("#{self.site}?UstId_1=DE123456789&UstId_2=#{ust_id}") )
    end # #get
  end # class << self
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  before_action :authenticate_user!
  before_action :set_locale

  protected

  def set_locale
    cookies['locale'] = params.permit(:locale)[:locale]  if params.permit(:locale)[:locale].present?
    I18n.locale       = cookies['locale'] || :en
  end # #set_locale

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :delete, :pdf]

  before_action :only_allow_post_owner, only: [:edit, :update, :delete]

  def index
    @posts = BlogPost.page(params[:page]).per(25)
    # example of cookie overflow:
    # flash[:notice] = Faker::Lorem.paragraph * 1000
  end # #index
  
  def new
    @post = BlogPost.new
  end # #new

  def create
    @post = BlogPost.new(permitted_params)
    @post.user = current_user
    if @post.save
      redirect_to @post
    else
      flash[:alert] = @post.errors.full_messages
      render :new
    end
    
  end # #create

  def show
    render :show
    # FIXME Mine Type Error (maybe bug in rails)
    #respond_to do |format|
      #format.html 
      #format.json { render json: @post }
      #format.yaml { render raw: @post.to_yaml }
      #format.pdf  { send_data(@post.to_pdf.read) }
    #end
  end # #show

  def edit
  end # #edit

  def update
    if @post.update_attributes(permitted_params)
      flash[:notice] = t('success')
      redirect_to edit_blog_post_path(@post)
    else
      flash[:alert] =  @post.errors.full_messages
      render :edit
    end
  end # #update


  def pdf
    file =  @post.to_pdf
    send_data file.read, type: 'application/pdf', disposition: 'inline'
  end # #pdf

  protected
  def set_post
    @post = BlogPost.find(params[:id])
  end # #set_post

  def only_allow_post_owner
    if @post.user != current_user
      redirect_to blog_posts_path
    end
  end # #only_allow_post_owner

  def permitted_params
  params.require(:blog_post).permit(:title, :body, :public, :image)
  end # #permitted_params
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @books = Book.all
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    @book.book_chapters.build
    respond_with(@book)
  end

  def edit
    @book.book_chapters.build
  end

  def create
    @book = Book.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    #
    # {book: {title: 'test', user_id: 'bla'}}
    def book_params
      params.require(:book).permit(:title, :summary, :flags, {
        book_chapters_attributes: [
          :title,
          :body,
          :id,
          :_destroy, {
            author_ids: [],
            reviewer_ids: [],
          }
        ]
      })

    end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController

  def update
    I18n.locale = params.permit(:locale)[:locale]
    redirect_back(fallback_location: root_path)
  end # #update
end

app/controllers/names_controller.rb
class NamesController < ApplicationController

  def form
    if permitted_params[:name]
      @names = NameApi.get_frequency(permitted_params[:name])
    else
      @names = []
    end
  end # #name

  protected

  def permitted_params()
    if params.present?
      params.permit(:name)
    else
      {}
    end
  end # #permitted_params

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def request
    
  end # #request

  def inform_authors
    
  end # #
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(msg)
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(msg).html_safe
  end # #markdown

  def flash_as_array(flash_msg)
    if flash_msg.kind_of?(Array) 
     return flash_msg 
    else
     return [flash_msg]   
    end
  end # #flash_as_array

  def object_new?(form)
    return !form.object.persisted?
  end # #object_new?


end

app/helpers/book_chapters_helper.rb
module BookChaptersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blog_posts/_form.haml
.container
  .row
    .col-md-2
    .col-md-6
      = form_for(@post) do |f|
        .form-group
          = f.label :title
          = f.text_field :title, size: 45, class: 'form-control'
        .form-group
          = f.text_area :body, cols: 45, rows: 30, class: 'markdown-editor-wysiwyg'
        .form-group
          = f.label :public
          = f.check_box :public
        .form-group
          .container
            .row
              .col-md-1
                - if @post.image.present?
                  %img{src: @post.image.url}
                -#- if @post.image.attachment.present?
                  -#%img{src: url_for(@post.image.variant(resize: "100x100"))}
              .col-md-6
                = f.file_field :image
        .form-group.btn
          = f.submit

app/views/blog_posts/_posts.haml
- @posts.each do |post| 
  .row.blog-post-entry{id: dom_id(post)}
    .col
      %h4
        = l(post.created_at, format: :short) 
        = post.title 
        = link_to edit_blog_post_path(post) do 
          %span.glyphicon.glyphicon-pencil{'aria-hidden' => "true"}
    .col
      .container
        .row
          .col-md-2
            - if post.image.attachment.present?
              %img.thumbnail{src: url_for(post.image.variant(resize: '120x120'))}
            - else
              %img.thumbnail{src: 'http://via.placeholder.com/120x120'}
          .col-md-6
            = truncate(markdown(post.body), length: 250) do 
              = link_to( t('blog_posts.index.show_blog_post'), blog_post_path(post.id), class: 'btn btn-primary')
        .row
          %hr
          = link_to 'Download', pdf_blog_post_path(post.id), class: 'btn' 

app/views/blog_posts/_posts_table.haml
.row
  %table.table.table-striped
    %tr
      %th= BlogPost.human_attribute_name(:title)
      %th= BlogPost.human_attribute_name(:body)
      %th= BlogPost.human_attribute_name(:created_at)
      %th= t('actions')
    - blog_posts.each do |post|
      %tr{class: cycle('even', 'odd')}
        %td= post.title
        %td
          = truncate(markdown(post.body).html_safe, length: 25) do 
            = link_to( t('blog_posts.index.show_blog_post'), blog_post_path(post.id), class: 'btn btn-primary')
        %td= l(post.created_at)
        %td
          = link_to t('edit'), edit_blog_post_path(post, locale: I18n.locale)
          = link_to t('blog_posts.index.show_blog_post'), blog_post_path(post, locale: I18n.locale)
          = link_to 'Download', pdf_blog_post_path(post.id, locale: I18n.locale), class: 'btn'

app/views/blog_posts/edit.haml
%center
  %h2= t('.title', title: @post.title)

= render partial: 'form'

app/views/blog_posts/index.haml
%h2= t('.posts_title')

.container
  .row
    = link_to t('create'), new_blog_post_path 
  .row
    = paginate @posts 
  = render partial: 'posts_table', locals: {blog_posts: @posts}
  .row
    = paginate @posts 

app/views/blog_posts/new.haml
%center
  %h2= t('.title', title: @post.title)

= render partial: 'form'

app/views/blog_posts/show.html.erb
<div class="">
<h1><%= @post.title %></h1>

<div class="well">
  <%= markdown(@post.body) %>
</div>
<%= link_to t('back'), :back %>

app/views/names/form.haml
- form_for 'names', url: names_path do | f|
  = f.text_field :name

.container
  .row
    .col-md-2
      = @names[:name]
    .col-md-6
      - @names[:countries].each do |country|
        = country

app/views/welcome/index.haml
.container-fluid
  .row
    .col-md-4
    .col-md-4
      .well
        %center
          = link_to blog_posts_path do
            %h1 Welcome
    .col-md-4
  