config/routes.rb
Rails.application.routes.draw do
  resources :book_chapters
  resources :books
  devise_for :users
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #

  resources :reviews, only: [] do
    collection do
      post :request
      post :inform_authors
    end
  end

  scope('(/:locale)') do
    resources :blog_posts do
      member do
        get :pdf
      end
    end

    resource :locales

    # get 'welcome'=>  'welcome#index'
    match '/welcome' => 'welcome#index', :via => [:get, :post]

    match '/names' => 'names#form', :via => [:get, :post]
  end

  root 'blog_posts#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

  validates :title, :body, presence: true

  #has_one_attached :image
  has_attached_file :image, style: { medium: "100x100>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user

  include Rails.application.helpers


  def pdf_path
    Rails.root.join('tmp', "#{self.id}.pdf")
    
  end # #pdf_path

  def to_pdf
    Prawn::Document.generate(pdf_path) do |pdf|
      pdf.text self.title
      pdf.text markdown(self.body)
    end
    File.open(pdf_path)
  end # #to_pdf
end

app/models/book.rb
class Book < ApplicationRecord
  include FlagShihTzu

  has_many :book_chapters
  has_flags(
    1 => :published,
    2 => :on_sale
  )

  accepts_nested_attributes_for :book_chapters, reject_if: proc {|attributes|
    attributes['_destroy'].blank? and attributes['title'].blank? 
  }, allow_destroy: true

end

app/models/book_chapter.rb
class BookChapter < ApplicationRecord
  belongs_to :book

  has_and_belongs_to_many :authors, class_name: 'User', join_table: :book_chapters_authors

  has_and_belongs_to_many :reviewers, class_name: 'User', join_table: :book_chapters_reviewers
  
end

app/models/name_api.rb
class NameApi
  class << self
    
    def site
     URI('http://www.thomas-bayer.com/restnames/name.groovy')
    end # .site

    def get_frequency(name)
      Hash.from_xml(
        RestClient.get("#{self.site}?name=#{name}")
      )[:restnames][:nameinfo]
    end # .get_frequency
  end # class << self

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
    :omniauthable, :registerable, 
    :recoverable, :rememberable, :trackable, :validatable

  has_many :blog_posts
end

app/models/vat_id.rb
class VatId

  class << self

    def site
      'https://evatr.bff-online.de/evatrRPC'
    end # #site

    def get(ust_id)
      Hash.from_xml( RestClient.get("#{self.site}?UstId_1=DE123456789&UstId_2=#{ust_id}") )
    end # #get
  end # class << self
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @books = Book.all
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    @book.book_chapters.build
    respond_with(@book)
  end

  def edit
    @book.book_chapters.build
  end

  def create
    @book = Book.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    #
    # {book: {title: 'test', user_id: 'bla'}}
    def book_params
      params.require(:book).permit(:title, :summary, :flags, {
        book_chapters_attributes: [
          :title,
          :body,
          :id,
          :_destroy, {
            author_ids: [],
            reviewer_ids: [],
          }
        ]
      })

    end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController

  def update
    I18n.locale = params.permit(:locale)[:locale]
    redirect_back(fallback_location: root_path)
  end # #update
end

app/controllers/names_controller.rb
class NamesController < ApplicationController

  def form
    if permitted_params[:name]
      @names = NameApi.get_frequency(permitted_params[:name])
    else
      @names = []
    end
  end # #name

  protected

  def permitted_params()
    if params.present?
      params.permit(:name)
    else
      {}
    end
  end # #permitted_params

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def request
    
  end # #request

  def inform_authors
    
  end # #
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(msg)
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(msg).html_safe
  end # #markdown

  def flash_as_array(flash_msg)
    if flash_msg.kind_of?(Array) 
     return flash_msg 
    else
     return [flash_msg]   
    end
  end # #flash_as_array

  def object_new?(form)
    return !form.object.persisted?
  end # #object_new?


end

app/helpers/book_chapters_helper.rb
module BookChaptersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_head.haml
%head
  %meta{charset: "utf-8"}
  %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}

  = csrf_meta_tags
  = csp_meta_tag 

  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
  :javascript
    window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#eaf7f7",
          "text": "#5c7291"
        },
        "button": {
          "background": "#56cbdb",
          "text": "#ffffff"
        }
      },
      "content": {
        "message": "This website uses cookies to ensure you get the best experience on our website.",
        "dismiss": "Got it!",
        "link": "Learn more",
        "href": "http://cookies.insites.com/about-cookies"
      }
    })});

  %title
    Hello, world!

app/views/layouts/_navigation.haml
%nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
  .container-fluid
    .navbar-header
      %a.navbar-brand{href: "/"}
        My first Blog
      %ul.nav.navbar-nav
        %li
          = link_to Book.model_name.human, books_path
        %li
          = link_to 'EN', locales_path(locale: :en), method: :patch 
        %li
          = link_to 'DE', locales_path(locale: :de), method: :patch 
    .collapse.navbar-collapse.pull-right
      .navbar-header
        %a.navbar-brand{href: 'javascript:;'}
          %img.thumbnail#zoom{src: asset_path('Daily-Boxes-2-300px.png')} 
        %ul.nav.navbar-nav
          - if current_user
            %li
              %a{href: 'javascript:;'}
                = current_user.email
            %li
              = link_to 'log out', destroy_user_session_path, method: :delete 

app/views/layouts/application.haml
<!doctype html>
%html{lang: "en"}
  = render partial: 'layouts/head'
  %body
    = render partial: 'layouts/navigation'
    .container-fluid
      .row
        .col-md-12#skip-navbar
      .row
        - if notice.present? 
          - flash_as_array(notice).each do |msg| 
            .alert.alert-success.alert-dismissible{role: "alert"}
              %button.close{type: "button", 'data-dismiss' => "alert", 'aria-label'=>"Close"}
                %span{'aria-hidden'=>"true"}
                  &times;
            = msg 
        - if alert.present? 
          - flash_as_array(alert).each do |msg| 
            .alert.alert-danger.alert-dismissible{role: "alert"}
              %button.close{type:"button", 'data-dismiss' => "alert", "aria-label" =>"Close"}
                %span{"aria-hidden" => true}
                  &times;
            = msg 
      .row
        = yield 

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">
        My first Blog
      </a>
      <%= link_to 'log out', destroy_user_session_path, method: :delete %>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <% if notice.present? %>
          <% flash_as_array(notice).each do |msg| %>
          <div class="alert alert-success alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= msg %>
          </div>
          <% end %>
        <% end %>
        <p class="alert"><%= alert %></p>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application_old.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-default">

      <a class="navbar-brand" href="/">
        My first Blog
      </a>
      <%= link_to 'EN', locales_path(locale: :en), method: :patch %>
      <%= link_to 'DE', locales_path(locale: :de), method: :patch %>
      <%= image_tag(asset_path('Daily-Boxes-2-300px.png')) %>
      <%= link_to 'log out', destroy_user_session_path, method: :delete %>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <% if notice.present? %>
          <% flash_as_array(notice).each do |msg| %>
          <div class="alert alert-success alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= msg %>
          </div>
          <% end %>
        <% end %>
        <%# flash[:alert] %>
        <% if alert.present? %>
          <% flash_as_array(alert).each do |msg| %>
          <div class="alert alert-danger alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= msg %>
          </div>
          <% end %>
        <% end %>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/welcome.haml
<!doctype html>
%html{lang: "en"}
  = render partial: 'layouts/head'
  %body
    .container-fluid
      .row
        .col-md-12#skip-navbar
      .row
        - if notice.present? 
          - flash_as_array(notice).each do |msg| 
            .alert.alert-success.alert-dismissible{role: "alert"}
              %button.close{type: "button", 'data-dismiss' => "alert", 'aria-label'=>"Close"}
                %span{'aria-hidden'=>"true"}
                  &times;
            = msg 
        - if alert.present? 
          - flash_as_array(alert).each do |msg| 
            .alert.alert-danger.alert-dismissible{role: "alert"}
              %button.close{type:"button", 'data-dismiss' => "alert", "aria-label" =>"Close"}
                %span{"aria-hidden" => true}
                  &times;
            = msg 
      .row
        = yield 